### ISSUE TITLE
test heavy concurrency

### ISSUE THREAD

**Issue by wumb0** [wumb0/metapwn#9]
might need to have each module have it's own RPC connection...

**Comment by wumb0** [comment]
I think this happens when things are run too quickly
```python
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "metapwn.py", line 128, in main
    svcs = self.get_services(proto, ports, True)
  File "metapwn.py", line 139, in get_services
    return set([(x[b'host'], x[b'port']) for x in self.client.db_services(ports=ports, protocol=proto, only_up=True)['services']])
  File "/work/msfcore.py", line 63, in db_services
    return self.call('db.services', kwargs)
  File "/work/msfcore.py", line 68, in call
    return self.rpc.call(query, opts)
  File "/work/metasploit/src/metasploit/msfrpc.py", line 254, in call
    self.client.request('POST', self.uri, packb(l), self._headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1141, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.5/http/client.py", line 974, in putrequest
    raise CannotSendRequest(self.__state)
http.client.CannotSendRequest: Request-sent
```

**Comment by wumb0** [comment]
Worked wonderfully. Launched >200 jobs in 2 mins
